name: 'ping-web'
services:
  frontend:
    build:
      context: ./docker
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
  vite:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
      #- /app/node_modules # Prevent node_modules issues
    ports:
      - "8081:8081"
    depends_on: [frontend]
    command: ["sh", "-c", "npm install && npm run dev -- --host"]